### ISSUE TITLE
cemerick.pomegranate dependency?

### ISSUE THREAD

**Issue by pdenno** [roryk/clojupyter#13]
This is more a very basic question than an issue: How are others loading their application into a notebook? Or are you building a kernel with everything you need in the classpath? I added cemerick.pomegranate as a dependency, and then loaded my stuff:

`(use '[cemerick.pomegranate :only (add-dependencies) :as pom])`
` (pom/add-dependencies :coordinates '[[gov.nist/closmop "0.1.0-SNAPSHOT"]])`
`(use '[gov.nist.closmop])`

Is that something worth adding to clojupyter's dependencies?
Clojupyter is great, by the way! I'm going to find lots of uses for it, I think.

**Comment by roryk** [comment]
Thanks for implementing this as well, it makes the kernel actually useful for something more than a toy.
