### ISSUE TITLE
Printing to stdout no longer works

### ISSUE THREAD

**Issue by thomasjm** [roryk/clojupyter#20]
Just opening an issue to track this -- see also my comment on the PR that introduced the regression: https://github.com/roryk/clojupyter/pull/14

It is no longer possible to print to stdout (i.e. something like `(prn "HI")`) with this kernel.

CC @pdenno  @roryk

**Comment by roryk** [comment]
Hi everyone, 

Thanks-- I'm not sure how stdout gets captured via the nrepl middleware, but if we can capture that and send it along the iopub socket we should be good to go.

**Comment by roryk** [comment]
Thanks Thomas, I fixed this:

```
Jupyter Console 4.1.1

Input configuration: {:transport tcp, :hb_port 64694, :kernel_name clojure, :ip 127.0.0.1, :control_port 64693, :key ccb7f60f-1535-4ec6-ac83-6a96cf92e445, :stdin_port 64692, :signature_scheme hmac-sha256, :shell_port 64690, :iopub_port 64691}
Connecting heartbeat to tcp://127.0.0.1:64694
Connecting shell to tcp://127.0.0.1:64690
Connecting iopub to tcp://127.0.0.1:64691

In [1]: (println "foo")
WARNING: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to False.
foo
Out[1]: nil
```

**Comment by thomasjm** [comment]
Awesome, thanks @roryk! Question, does this solution capture stderr as well? It's slightly less important, but some Jupyter kernels do print to stderr. Maybe the `nrepl` exception capturing stuff is sufficient though.

**Comment by roryk** [comment]
Hi Thomas,

I added capturing in stderr as well, thanks for the suggestion!

**Comment by thomasjm** [comment]
Perfect, thanks for the quick turnaround!
