### ISSUE TITLE
Make fails: bin/ and bin/clojupyter.template do not exist

### ISSUE THREAD

**Issue by pcallier** [roryk/clojupyter#21]
Make fails on ubuntu 16.04 with the following message. I can only imagine it would also fail on most platforms, since bin/ and its contents went away after 7f13c72af2db6ad7aba33d6368a7f1cc3fae2fab and that seems to have something to do with it?

Let me know if I'm missing something obvious.

```
lein uberjar
Compiling clojupyter.core
Compiling clojupyter.core
Created /home/patrick/clojupyter/target/clojupyter-0.1.0-SNAPSHOT.jar
Created /home/patrick/clojupyter/target/clojupyter-0.1.0-SNAPSHOT-standalone.jar
cat bin/clojupyter.template $(find . -maxdepth 2 -type f | grep -e ".*standalone.*\.jar") > bin/clojupyter
/bin/sh: 1: cannot create bin/clojupyter: Directory nonexistent
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by roryk** [comment]
Thanks for the fix, I fixed the .gitignore as well which was masking this problem.
