### ISSUE TITLE
Multiple expression return value is printed without new line

### ISSUE THREAD

**Issue by woosley** [roryk/clojupyter#23]
hello! 
If I input 2 expressions, I will get all return value printed on the same line, is it possible to add line break between different return values?

```
(+ 1 2)
(+ 2 3)
3 5
```

**Comment by roryk** [comment]
Hi Woosley,

I'm worried about changing the actual output from what it really is. One expression per output you want to see seems like a good idea for using the notebook.

**Comment by roryk** [comment]
This should be fixed now with the autocompletion check, now you can't enter more than one complete expression, hitting enter sends the current expression to be evaluated if it is complete. Thanks!
