### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by ghost** [roryk/clojupyter#37]
```
c019020:clojupyter aidanrocke$ make
lein uberjar
make: lein: No such file or directory
make: *** [all] Error 1
```

I installed clojure as described [here](https://clojure.org/guides/getting_started) and I must note that I'm new to using clojure but the REPL works without a problem.

**Comment by luojieshun** [comment]
Have you installed Leiningen? The Clojure build tool?
Try 

> lein repl

And see if it works. Or follow this to install it

> https://leiningen.org/#install

**Comment by didiercrunch** [comment]
As this issue is quite old and very user specific, I will close it.  If you encounter the issue again, please fell free to contact me and I will help you offline.

cheers,

didier
