### ISSUE TITLE
ZMQException

### ISSUE THREAD

**Issue by tcfuji** [roryk/clojupyter#7]
Getting the following after running `jupyter notebook` and creating a new clojure notebook:

```
[I 23:52:13.641 NotebookApp] Creating new notebook in
[I 23:52:14.824 NotebookApp] Kernel started: 953b593d-ce73-4c77-b3f9-b3c7b5e287b2
Input configuration: {:transport tcp, :iopub_port 62456, :key 2dde9a9a-140e-4bc9-b82a-1021e6697943, :signature_scheme hmac-sha256, :shell_port 62455, :stdin_port 62457, :control_port 62458, :hb_port 62459, :ip 127.0.0.1}
Connecting heartbeat to tcp://127.0.0.1:62459
Connecting shell to tcp://127.0.0.1:62455
Connecting iopub to tcp://127.0.0.1:62456
Exception in thread "main" org.zeromq.ZMQException: Errno 65 :
	at org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:1344)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1209)
	at zeromq.zmq$send.invoke(zmq.clj:159)
	at ipython_clojure.core$send_message_piece.invoke(core.clj:48)
	at ipython_clojure.core$kernel_info_reply.invoke(core.clj:86)
	at ipython_clojure.core$configure_shell_handler$fn__1603.invoke(core.clj:298)
	at ipython_clojure.core$shell_loop.invoke(core.clj:332)
	at ipython_clojure.core$_main.doInvoke(core.clj:346)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at ipython_clojure.core.main(Unknown Source)
[W 23:52:24.894 NotebookApp] Timeout waiting for kernel_info reply from 953b593d-ce73-4c77-b3f9-b3c7b5e287b2
```

**Comment by roryk** [comment]
Hi @tcfuji,

Something might be borked with your IPython install, does anything in this thread https://github.com/jupyter/notebook/issues/297 help? Can you get a non-clojupyter notebook/kernel up and running?

Sorry to not have any answers out of the box, but we need some more information.

**Comment by tcfuji** [comment]
Thanks @roryk. I use Python and Haskell Jupyter notebooks too and they seem to be working fine.

If it matters, I also use pyenv and virtualenv, which has caused some other headaches in the past.

**Comment by tggreene** [comment]
Having the same issue:

    [I 11:15:30.195 NotebookApp] Kernel started: b6bc04ff-cfc6-44f5-9714-c46377992bbb
    Input configuration: {:transport tcp, :iopub_port 50361, :key 3dc87420-d393-4c9b-b7d0-ce701d809478, :signature_scheme hmac-sha256, :shell_port 50360, :stdin_port 50362, :control_port 50363, :hb_port 50364, :ip 127.0.0.1}
    Connecting heartbeat to tcp://127.0.0.1:50364
    Connecting shell to tcp://127.0.0.1:50360
    Connecting iopub to tcp://127.0.0.1:50361
    Exception in thread "main" org.zeromq.ZMQException: Errno 65 :
	    at org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:1344)
	    at org.zeromq.ZMQ$Socket.send(ZMQ.java:1209)
	    at zeromq.zmq$send.invoke(zmq.clj:159)
	    at ipython_clojure.core$send_message_piece.invoke(core.clj:48)
	    at ipython_clojure.core$kernel_info_reply.invoke(core.clj:86)
	    at ipython_clojure.core$configure_shell_handler$fn__1603.invoke(core.clj:298)
	    at ipython_clojure.core$shell_loop.invoke(core.clj:332)
	    at ipython_clojure.core$_main.doInvoke(core.clj:346)
	    at clojure.lang.RestFn.applyTo(RestFn.java:137)
	    at ipython_clojure.core.main(Unknown Source)
    [W 11:15:40.244 NotebookApp] Timeout waiting for kernel_info reply from b6bc04ff-cfc6-44f5-9714-c46377992bbb

[Host unreachable](https://github.com/zeromq/jeromq/blob/698d450266a36cca9da4d8194a4d43fe9e6a8140/src/main/java/zmq/ZError.java#L76) just can't work out why I'd be getting that in this context!

**Comment by huangjs** [comment]
Same problems here, but restart the kernel will make it work.

Looks like it's a timing issue?

**Comment by codinguncut** [comment]
same here, thank you huangjs, restarting the kernel did indeed work for me.

**Comment by roryk** [comment]
Thanks for figuring out what was up, sorry to be quiet. Do you think if we just set the timeout to be longer that this problem would resolve itself? If so we can try bumping up the default.

**Comment by boathit** [comment]
Same problem in Mac OS X 10.10.5 and restart the kernel from the button in jupyter notebook can make it work, weird.

**Comment by KimStebel** [comment]
Same issue here, restarting the kernel also makes it work, but that won't be an option for use with tmpnb and thebe. I'm using Ubuntu 14.04 in a docker container.

**Comment by KimStebel** [comment]
To reproduce the error, run

```
docker run --net=host kimstebel/thebe-demo-notebook:clojupyter-issue-7 jupyter notebook --no-browser --NotebookApp.base_url=/ --ip=0.0.0.0 --port 8080 --NotebookApp.allow_origin='*'
```

Then go to localhost:8080 and open a new Clojure notebook. I doubt increasing the timeout would help, since the kernel throws an exception while trying to answer the `kernel_info` message, so there won't ever be an answer to that message.

**Comment by roryk** [comment]
Thanks Kim for the instructions regarding how to reproduce, that is super helpful. I'll have some time to figure out what is going on this weekend.

**Comment by adampash** [comment]
Without intending to pile on, I'm running into the same problem, and would be happy to provide any information you might need to help debug. I'm new to clojure, so I might not be the most helpful, but I'll happily do anything I can!

**Comment by adampash** [comment]
I just spent a little time with this and found that if I commented out `(zmq/set-router-mandatory shell-socket true)` that everything works as expected without the above error:

```clojure
    ;; Detect problems when using router socket
    ;; (zmq/set-router-mandatory shell-socket true)
```

**Comment by roryk** [comment]
Hi Adam,

Thank you so much for figuring out a work around, I added you as a collaborator so you can push to the repository. I think it would be better to catch these exceptions and log a message but for now this at least gets things up and going. I owe you a beverage of your choice.
