### ISSUE TITLE
syntax error/exception not shown in notebook

### ISSUE THREAD

**Issue by codinguncut** [roryk/clojupyter#8]
I just put this code in my notebook '(if (=1 1) "true" "false")'.

Observed:
On my terminal, the output was "Unable to resolve symbol =1", but notebook didn't show any error output.

Expected:
Notebook output to show error/trace/exception

**Comment by roryk** [comment]
Thanks @codinguncut, there was a bug that was sending back an 'ok' message when there was an exception. I fixed that and we can actually see the exceptions now.
